### ISSUE TITLE
Explain usage details in README

### ISSUE THREAD

**Issue by taurauko** [StudistCorporation/ring-accept-language#4]
It would be very helpful if you showed an example of what this middleware injects where in the request map.

**Comment by Invertisment** [comment]
Import from here: https://clojars.org/jp.studist/ring-accept-language

Use like this:
```
(ns my-ns 
  (:require [ring.middleware.accept-language :as accept-language]))

(defn get-best-language-list [req]
  (->> req ;; {:headers {"accept-language" "en-US,en;q=0.5"}}
       (accept-language/accept-language-request)
       :accept-language
       (sort-by second #(compare %2 %1))))
```
If `req` is the same as in the comment then this is the output:
`(["en-US" 1.0] ["en" 0.5])`

If you prefer to use it for all requests then you should use it as other ring's middleware like this one:
https://github.com/ngrunwald/ring-middleware-format#usage
